# Generated by Django 4.1 on 2024-10-16 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wb', '0004_alter_productmodel_brand_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='brand_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='vendor_code',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
